-- Sentinel -- Autonomous Incident Commander
-- Phase 1a: Core schema
--
-- Run this file first, in this order: 01 -> 02 -> 03 -> 04 -> 05.
-- In Oracle's SQL worksheet / SQL*Plus / SQLcl, run the whole file at once.

CREATE TABLE services (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR2(100) NOT NULL,
    description     VARCHAR2(500),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_services PRIMARY KEY (id),
    CONSTRAINT uq_services_name UNIQUE (name)
);

CREATE TABLE runbooks (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    fault_signature     VARCHAR2(100) NOT NULL,
    title               VARCHAR2(200) NOT NULL,
    remediation_steps   VARCHAR2(2000) NOT NULL,
    risk_level          VARCHAR2(10) NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_runbooks PRIMARY KEY (id),
    CONSTRAINT ck_runbooks_risk CHECK (risk_level IN ('LOW','MEDIUM','HIGH'))
);

-- incident_number (e.g. "INC-0001") is populated by trg_incident_number in
-- 02_triggers.sql, using this sequence -- kept separate from the internal
-- identity PK, the same way Jira/PagerDuty separate their ticket numbers
-- from their internal row IDs.
CREATE SEQUENCE seq_incident_number START WITH 1 INCREMENT BY 1;

CREATE TABLE incidents (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    incident_number VARCHAR2(20),
    service_id      NUMBER NOT NULL,
    status          VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    severity        VARCHAR2(10) NOT NULL,
    title           VARCHAR2(200) NOT NULL,
    description     VARCHAR2(1000),
    root_cause      VARCHAR2(1000),
    detected_by     VARCHAR2(50) DEFAULT 'monitor_agent' NOT NULL,
    started_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    resolved_at     TIMESTAMP,
    CONSTRAINT pk_incidents PRIMARY KEY (id),
    CONSTRAINT uq_incidents_number UNIQUE (incident_number),
    CONSTRAINT fk_incidents_service FOREIGN KEY (service_id) REFERENCES services(id),
    CONSTRAINT ck_incidents_status CHECK (status IN
        ('OPEN','DIAGNOSING','AWAITING_APPROVAL','REMEDIATING','MONITORING','RESOLVED')),
    CONSTRAINT ck_incidents_severity CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL'))
);

CREATE TABLE incident_events (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    incident_id     NUMBER NOT NULL,
    event_type      VARCHAR2(30) NOT NULL,
    agent_name      VARCHAR2(50),
    message         VARCHAR2(2000) NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_incident_events PRIMARY KEY (id),
    CONSTRAINT fk_events_incident FOREIGN KEY (incident_id)
        REFERENCES incidents(id) ON DELETE CASCADE
);

CREATE TABLE agent_actions (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    incident_id     NUMBER NOT NULL,
    runbook_id      NUMBER,
    agent_name      VARCHAR2(50) NOT NULL,
    action_type     VARCHAR2(50) NOT NULL,
    target_service  VARCHAR2(100),
    risk_level      VARCHAR2(10) NOT NULL,
    status          VARCHAR2(20) DEFAULT 'PROPOSED' NOT NULL,
    result          VARCHAR2(1000),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    executed_at     TIMESTAMP,
    CONSTRAINT pk_agent_actions PRIMARY KEY (id),
    CONSTRAINT fk_actions_incident FOREIGN KEY (incident_id)
        REFERENCES incidents(id) ON DELETE CASCADE,
    CONSTRAINT fk_actions_runbook FOREIGN KEY (runbook_id) REFERENCES runbooks(id),
    CONSTRAINT ck_actions_risk CHECK (risk_level IN ('LOW','MEDIUM','HIGH')),
    CONSTRAINT ck_actions_status CHECK (status IN
        ('PROPOSED','APPROVED','REJECTED','EXECUTED','FAILED'))
);

CREATE TABLE approvals (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    agent_action_id     NUMBER NOT NULL,
    requested_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    decided_at          TIMESTAMP,
    decided_by          VARCHAR2(100),
    decision            VARCHAR2(10),
    notes               VARCHAR2(1000),
    CONSTRAINT pk_approvals PRIMARY KEY (id),
    CONSTRAINT fk_approvals_action FOREIGN KEY (agent_action_id)
        REFERENCES agent_actions(id) ON DELETE CASCADE,
    CONSTRAINT ck_approvals_decision CHECK (decision IN ('APPROVED','REJECTED'))
);

CREATE TABLE postmortems (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    incident_id     NUMBER NOT NULL,
    content         CLOB NOT NULL,
    generated_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_postmortems PRIMARY KEY (id),
    CONSTRAINT uq_postmortems_incident UNIQUE (incident_id),
    CONSTRAINT fk_postmortems_incident FOREIGN KEY (incident_id)
        REFERENCES incidents(id) ON DELETE CASCADE
);

CREATE TABLE metrics_snapshot (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    service_id      NUMBER NOT NULL,
    metric_name     VARCHAR2(50) NOT NULL,
    metric_value    NUMBER NOT NULL,
    recorded_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_metrics_snapshot PRIMARY KEY (id),
    CONSTRAINT fk_metrics_service FOREIGN KEY (service_id)
        REFERENCES services(id) ON DELETE CASCADE
);

-- Indexes -- every foreign key that gets queried heavily (status filters,
-- timeline lookups) earns one. Oracle does NOT auto-index FK columns the
-- way some other databases do, so these are deliberate, not defaults.
CREATE INDEX idx_incidents_status ON incidents(status);
CREATE INDEX idx_events_incident ON incident_events(incident_id);
CREATE INDEX idx_actions_incident ON agent_actions(incident_id);
CREATE INDEX idx_metrics_service_time ON metrics_snapshot(service_id, recorded_at);
